apiVersion: apps/v1
kind: Deployment
metadata:
  name: ida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ida
  template:
    metadata:
      labels:
        app: ida
    spec:
      containers:
      - name: ida
        image: mcr.microsoft.com/dotnet/core/aspnet:3.1
        ports:
        - containerPort: 80
        - containerPort: 443
        command: ["dotnet"]
        args: ["CognitiveSearch.UI.dll"]
        volumeMounts:
          - name: ida
            mountPath: /mnt/ida
        workingDir: /mnt/ida
      volumes:
      - name: ida
        azureFile:
          secretName: azure-secret
          shareName: ida
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: ida
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: ida
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ida
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: {{host}}
    http:
      paths:
      - backend:
          serviceName: ida
          servicePort: 80
        path: /