apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyspark
  template:
    metadata:
      labels:
        app: pyspark
    spec:
      containers:
      - name: pyspark
        image: honorubu/jupyter-blobfuse:0.21alpha
        ports:
        - containerPort: 8888
        - containerPort: 4040
        - containerPort: 4041
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add: ["SYS_ADMIN"]
        lifecycle:
          postStart:
            exec: 
              command: ["/bin/sh", "-c", "
                        printf \"accountName {{storage_account}}\naccountKey {{storage_key}}\ncontainerName {{container_name}}\" > ./fuse.cfg;
                        blobfuse ./data --tmp-path=/tmp/blobfuse --config-file=./fuse.cfg;
                        rm ./fuse.cfg" ]
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token={{login_token}}"]
---
apiVersion: v1
kind: Service
metadata:
  name: pyspark
spec:
  type: ClusterIP
  ports:
  - name: webui
    port: 8888
    targetPort: 8888
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "4041"
    port: 4041
    targetPort: 4041
  selector:
    app: pyspark
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pyspark
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: {{host}}
    http:
      paths:
      - backend:
          serviceName: pyspark
          servicePort: 8888
        path: /