apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: apache/tika
        ports:
        - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
  name: tika
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 9998
  selector:
    app: tika
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tika
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  rules:
  - host: {{host}}
    http:
      paths:
      - backend:
          serviceName: tika
          servicePort: 9998
        path: /